### ISSUE TITLE
MIUI 11 PORTUGUESE

### ISSUE THREAD

**Issue by vidoca** [KcNirvana/MIUI-XML-11-PORTUGUESE#35]
boa noite,
após a instalação da rom para mi6, ao reiniciar recebo a mensagem que o aparelho se encontra associado a uma conta que não é a minha.
è possivel alguma ajuda?

**Comment by KcNirvana** [comment]
Boas...
Tens que ir à loja onde compraste para eles te tirarem isso.
Ou então se compraste a alguém falar com essa pessoa para retirar o telefone da conta dela.
Abraço
