### ISSUE TITLE
Ajuda - Tradução PT-BR

### ISSUE THREAD

**Issue by RicardoGuariento** [KcNirvana/MIUI-XML-11-PORTUGUESE#48]
Amigo, não estou conseuindo encontrar essa linha para eu traduzir. Não consegui encontrar nem no repo PT-BR, PT-PT ou no Compare. 
Sabe onde ela está?

![Screenshot_2019-12-15-11-29-50-743_com miui packageinstaller](https://user-images.githubusercontent.com/46526008/70864195-9101ea80-1f2e-11ea-8271-5d83b2fad280.jpg)

**Comment by KcNirvana** [comment]
Boas...
Essa tradução está nas apks da google logo impossivel de ser traduzida.
product/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk

Abraço
